export App from './App/App';
export Authorization from './Authorization/Authorization';
export Registration from './Registration/Registration';
export ResetPassword from './ResetPassword/ResetPassword';
export Welcome from './Welcome/Welcome';
export Survey from './Survey/Survey';
export FormContainer from './FormContainer/FormContainer';
export Account from './Account/Account';
export Submit from './Submit/Submit';
